### PR TITLE
Add .editorconfig template

### LINKED ISSUE #30: Decision: EditorConfig (or similar) for core editor settings?
### Descriptive summary

It would be good if the @ucsdlib/developers could discuss/decide whether to adopt something like [Editor Config](https://editorconfig.org/) to help our team manage consistent spacing/indention settings across our projects.  

### Rationale

First, not everyone on our team uses the same editor. This is not in any way a negative, on the contrary people should use what is most productive for them. However, one can look at damspas as an example of a codebase that has a wide variety of editor settings which has resulted in files that can be very difficult to review and/or update. Some editors "hide" this from users and automatically reformat files for a user to view, but this does not change the underlying text file. So simple text editors, like Vim or Emacs, will see these changes in a more dramatic way. 

Rubocop does help with this for Ruby projects, but wouldn't help for Java. Editor Config is more agnostic.

### PR DESCRIPTION
**Pull request by mcritchlow**
Fixes #30 

Hey all, here's a first pass at an initial template for using Editor Config in our projects. 

The ruby/web stuff seems right to me, but I'm curious about the java settings. Particularly from @lsitu who works in Java more regularly than the rest of us now.

Changes proposed in this pull request:
* Base/global settings for trimming whitespace, inserting a final newline, utf-8, and space indention
* Web/markup file settings
* Ruby file settings
* Java file settings
* Misc files (Dockerfile, Gemfile, etc.)

@ucsdlib/developers @jhriv  - please review

### CODE REVIEW

**Comment by hweng** [comment]
👍

**Review by jhriv — APPROVED** [review]
If language specific options override the default, why is there no default indent_size?

A default of 2 would make this file a lot simpler.

**Review by jhriv — CHANGES_REQUESTED** [review]
Should probably remove `root: true` as this will prevent a ~/.editorconfig from being read.

**Comment by VivianChu** [comment]
👍

**Comment by mcritchlow** [comment]
@jhriv 
> Should probably remove root: true as this will prevent a ~/.editorconfig from being read.

That might be desirable in some cases, but I think as a general starting point you're totally right. I'll comment that out and then move the `indent_size` bit up to the global section. I started doing the inventory of file types and then forgot to refactor it seems :)

**Review by jhriv — APPROVED** [review]

**Pull request merged**
