### PR TITLE
Add gitlab migration docs

### PR DESCRIPTION
**Pull request by mcritchlow**
This adds some documentation and a checklist for dev team members to
reference when migrating repositories from GitHub to GitLab

@ucsdlib/developers @rstanonik  - please review

### CODE REVIEW

**Review by VivianChu — APPROVED** [review]
👍 LGTM

**Comment by mcritchlow** [comment]
@VivianChu - Did I miss any steps you recall going through when setting up AP Batch?

**Comment by lsitu** [comment]
@mcritchlow Do you want me to migrate any projects at this time?

**Comment by mcritchlow** [comment]
@lsitu - Nope, not yet. This is just in preparation for the migration project kicking off. My hope in creating this is that all of us can contribute to it, and therefore have a higher comfort level with using GitLab's CI/CD system. I believe we'll be setting up a series of tickets in JIRA, possibly as early as next week, for all the repos we need to migrate.

**Review by lsitu — APPROVED** [review]
@mcritchlow Got it. Thanks. It looks good and the steps are straight forward. 👍

**Comment by VivianChu** [comment]
@mcritchlow - I think we just need to add more environment variables like TOMCAT_MANAGER_PRODUCTION_PASSWORD and TOMCAT_MANAGER_STAGING_PASSWORD for java deployment.
https://github.com/ucsdlib/DeveloperGuides/blob/37701a928f1badedfc05ba66018475fd98ec462e/templates/.gitlab-ci-java-tomcat.yml#L24
https://github.com/ucsdlib/DeveloperGuides/blob/37701a928f1badedfc05ba66018475fd98ec462e/templates/.gitlab-ci-java-tomcat.yml#L15

**Pull request merged**
