### PR TITLE
entire test suite should be run and pass prior to submitting a PR

### PR DESCRIPTION
**Pull request by mcritchlow**
Following some issues recently with PRs, I want to explicitly note this requirement for creating Pull Requests.

@VivianChu @hweng @dt-ucsd @lsitu I don't believe this is controversial enough to discuss at length, but please review this and comment with a :+1: when you have. Then I'll ask someone to merge. Thanks.

### CODE REVIEW

**Comment by VivianChu** [comment]
:+1:

**Comment by lsitu** [comment]
:+1:

**Comment by hweng** [comment]
:+1:

**Comment by mcritchlow** [comment]
@dt-ucsd can you please review?

**Comment by dt-ucsd** [comment]
Works for me. Thumbs up.

**Comment by mcritchlow** [comment]
Thanks all. Can someone merge please?

**Pull request merged**
