### PR TITLE
Add semantic versioning script

### PR DESCRIPTION
**Pull request by mcritchlow**
Also add scripts directory and documentation

See an example for High Five here: https://github.com/ucsdlib/hifive/releases/tag/1.3

Note, a user will still need to push the tag, the script does not assume you want that done immediately.

#### Local Checklist
- [ ] Tests written and passing locally?
- [ ] Code style checked?
- [ ] QA-ed locally?
- [x] Rebased with `master` branch?
- [ ] Configuration updated (if needed)?
- [x] Documentation updated (if needed)?

#### What does this PR do?
- Add `semver-bump` script
- Add documentation framing for it and future scripts

##### Why are we doing this? Any context of related work?
References #issuenumber

#### Manual testing steps?
For @ucsdlib/developers using Mac OS, it would be great if you can test this out. I intentionally wrote this script in POSIX-compliant `sh`, but it's possible there are some differences between some of the other binaries used such as `mktemp`, etc. So if a few of you could test in local test/dummy repos (or real ones and just delete the test tags) that would be great.

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by lsitu** [comment]
@mcritchlow It looks like it's working with my MAC. Thanks. I just see a minor error for the command `mktemp`. Here are the results I got with options for `patch` `minor` `major`:
``` 
$ ./scripts/semver-bump patch

usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
./scripts/semver-bump: line 70: : No such file or directory
./scripts/semver-bump: line 73: : No such file or directory
fatal: could not open or read '': No such file or directory
new version: 0.0.1
```

```
$ ./scripts/semver-bump minor

usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
./scripts/semver-bump: line 70: : No such file or directory
./scripts/semver-bump: line 73: : No such file or directory
fatal: could not open or read '': No such file or directory
new version: 0.1.0
```

```
$ ./scripts/semver-bump major
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
./scripts/semver-bump: line 70: : No such file or directory
./scripts/semver-bump: line 73: : No such file or directory
fatal: could not open or read '': No such file or directory
new version: 1.0.0
```

**Comment by mcritchlow** [comment]
@lsitu - thanks for the feedback! Darn, yeah it seems the mac os version of `mktemp` is very different than the standard linux version. I'll make an update and get back to you once i have a new commit. thank you for testing :)

**Comment by VivianChu** [comment]
@mcritchlow - I got the same error like Longshou.

**Comment by mcritchlow** [comment]
@lsitu, @VivianChu:

Thanks all, would you mind trying again? I've just updated the script to hopefully support the Mac OS version of `mktemp`

On Tue, Jun 04, 2019 at 10:06:39AM -0700, VivianChu wrote:
>@mcritchlow - I got the same error like Longshou.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ucsdlib/DeveloperGuides/pull/34#issuecomment-498759456

-- 
Thanks,

Matt Critchlow
UC San Diego Library

**Comment by VivianChu** [comment]
👍 It works for me. Looks good.  Thanks

**Review by VivianChu — APPROVED** [review]

**Comment by mcritchlow** [comment]
@VivianChu - would you mind pasting the output it generated in your test?

And to confirm, did your editor pop up giving you the option of editing the tag text? I just want to make sure everything is working for you all.

Thanks for testing!

On Tue, Jun 04, 2019 at 10:32:52AM -0700, VivianChu wrote:
>👍 It works for me. Looks good.  Thanks
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ucsdlib/DeveloperGuides/pull/34#issuecomment-498768755

-- 
Thanks,

Matt Critchlow
UC San Diego Library

**Comment by VivianChu** [comment]
@mcritchlow - Here are the screen shots. I think it use vi editor to open the file.

scriptOutput

//patch output
patch

//major
major

//minor
minor

**Comment by mcritchlow** [comment]
@VivianChu - ok this is very helpful, what this tells me is that you don't have an editor specified in your git configuration. If git doesn't see one specified, it defaults to vi. So I should add a reference in the documentation for this script that it should be setup.

Here's a reference: https://help.github.com/en/articles/associating-text-editors-with-git

**Comment by VivianChu** [comment]
@mcritchlow - I set default editor to atom - git config --global core.editor "atom --wait"
and the above command (major, minor, patch) is able to open atom editor.

**Comment by mcritchlow** [comment]
great! i added some docs to the scripts/README file, let me know if you think that's sufficient. thanks again for testing.

**Comment by VivianChu** [comment]
Looks good

**Pull request merged**
