### PR TITLE
rename tto to oic

### PR DESCRIPTION
**Pull request by mcritchlow**
The Technology Transfer Office has been renamed to the Office of Innovation and Commercialization. This update references accordingly.

### CODE REVIEW

**Comment by mcritchlow** [comment]
@ucsdlib/developers please take a look when you have a chance, thanks!

**Comment by lsitu** [comment]
👍

**Comment by VivianChu** [comment]
👍

**Comment by hweng** [comment]
👍

**Comment by mcritchlow** [comment]
thanks all and @hweng for the merge

**Pull request merged**
