### PR TITLE
Make PR template more template-y

### PR DESCRIPTION
**Pull request by mcritchlow**
While I'm at it, I've been thinking for a while that our current PR template in GitHub isn't that valuable. I've taken a different approach in this draft I quickly mocked up and I'm curious what you all think.

Changes proposed in this pull request:
* Local checklist: The idea here is a quick mental run through of things that should be done locally before this PR is actually submitted. Passing tests, rubocop and other linters, etc. Are there things that would be good to add or remove here?
* More emphasis put on context, the "why" this PR exists. In my opinion, having context really helps in understanding why the code is doing what it's doing. Making asking questions a bit easier and understanding where the developer was coming from.
* Sections for calling out new database migrations, environment variables, etc. that should be tested out and confirmed are working.

@ucsdlib/developers @jhriv - please review

### CODE REVIEW

**Review by jhriv — COMMENTED** [review]
You're using H4 (####) with no H3,2, or 1. I get that it's for visual instead of semantic.

Would  `-  *Section Description*` work? Provides visual clarity, and semantic meaningfulness. If no, the use of `####` is okay if weird looking.

#### New ENV Variables should have a reference to the issue in the relevant repo. Interesting chicken and egg, as they would need to cross-reference.

I don't think we have any sort of database change tracking repo. 

`Manual Testing Steps` should probably lack a ?
Honestly, I think all the section titles should lack a ? This is a template, not an interview.

**Comment by mcritchlow** [comment]
> You're using H4 (####) with no H3,2, or 1. I get that it's for visual instead of semantic. Would - *Section Description* work? Provides visual clarity, and semantic meaningfulness. If no, the use of #### is okay if weird looking.

Yeah, I admit that's there purely for what the viewing experience would be for someone when they're actually filling out the template. Not the underlying markup, which I agree does seem a bit odd.

> New ENV Variables should have a reference to the issue in the relevant repo. Interesting chicken and egg, as they would need to cross-reference.

No that's a great call, I'll put in a References example bit there too.

> I don't think we have any sort of database change tracking repo.

For this I meant more that it could be valuable to call out any database migrations, if any, and why.

> Manual Testing Steps should probably lack a ?
Honestly, I think all the section titles should lack a ? This is a template, not an interview.

I can see that. I guess I was thinking of it as a mix of template and self-interview. I could ditch the ?'s though if ya'll think it's unnecessary. I also suppose it goes without saying that irrelevant sections for a particular PR can/should just be removed or marked with N/A

**Review by jhriv — APPROVED** [review]
This works. Any other outstanding issues (like the unnecessary question marks) can be fixed in post (aka another PR)

**Comment by lsitu** [comment]
👍

**Comment by hweng** [comment]
:+1:

**Comment by VivianChu** [comment]
👍

**Pull request merged**
