### PR TITLE
added reference documentation interactive rebasing

### PR DESCRIPTION
**Pull request by mcritchlow**
To be used when following the git protocol for creating single commit pull requests

### CODE REVIEW

**Comment by mcritchlow** [comment]
@lsitu @dt-ucsd @VivianChu @hweng I've added some additional links for how to do interactive rebasing, to allow for single commit PRs. 
1. Can I get a :+1: from each of you if this looks good?
2. Follow that, I'll ask one of you to merge. Thanks!

**Comment by VivianChu** [comment]
:+1: looks good

**Comment by hweng** [comment]
:+1:

**Comment by lsitu** [comment]
:+1: It looks good to me.

**Comment by mcritchlow** [comment]
@dt-ucsd is out for a couple days, and I don't think this change is controversial. so we can move ahead with merging.

@VivianChu would you mind merging when you have a chance?

**Pull request merged**
